site_name: 我的中文文档
site_description: 基于 MkDocs-Material 的中文技术文档

theme:
  name: material
  language: zh  # 界面语言为中文
  palette:
    primary: indigo
    accent: blue
  features:
    - navigation.tabs
    - navigation.expand

plugins:
  - search:
      lang: zh  # 搜索支持中文
      separator: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  font:
    text: Inter
    code: Roboto Mono
